import { prisma } from "./db";

async function seed() {
  console.log("Seeding database...");

  // Clear existing
  await prisma.cartItem.deleteMany();
  await prisma.orderItem.deleteMany();
  await prisma.cart.deleteMany();
  await prisma.order.deleteMany();
  await prisma.product.deleteMany();

  const products = [
    // PUERTAS LISAS
    {
      slug: "puerta-lisa-l100",
      name: "Puerta Lisa L-100",
      code: "L-100",
      description: "Puerta interior lisa de melamina blanca. Acabado liso y uniforme.",
      price: 189.0,
      stock: 45,
      images: JSON.stringify(["/images/products/puerta-lisa.jpg"]),
      categoryId: "puertas",
      subcategoryId: "puertas-lisas",
      features: JSON.stringify(["Melamina blanca", "Marco incluido", "Bisagras incluidas"]),
      isActive: true,
    },
    {
      slug: "puerta-lisa-l110",
      name: "Puerta Lisa L-110 Natural",
      code: "L-110",
      description: "Puerta interior lisa en acabado roble natural. Elegante y duradera.",
      price: 229.0,
      stock: 30,
      images: JSON.stringify(["/images/products/puerta-lisa-natural.jpg"]),
      categoryId: "puertas",
      subcategoryId: "puertas-lisas",
      features: JSON.stringify(["Roble natural", "Marco incluido", "Alta resistencia"]),
      isActive: true,
    },
    {
      slug: "puerta-lisa-l120",
      name: "Puerta Lisa L-120 Gris",
      code: "L-120",
      description: "Puerta interior lisa en tono gris antracita. Diseño moderno.",
      price: 259.0,
      stock: 20,
      images: JSON.stringify(["/images/products/puerta-lisa-gris.jpg"]),
      categoryId: "puertas",
      subcategoryId: "puertas-lisas",
      features: JSON.stringify(["Gris antracita", "Acabado premium", "Marco incluido"]),
      isActive: true,
    },
    // PUERTAS FRESADAS
    {
      slug: "puerta-fresada-f520",
      name: "Puerta Fresada F-520",
      code: "F-520",
      description: "Puerta fresada con diseño de doble ranura. Elegancia clásica.",
      price: 320.0,
      stock: 15,
      images: JSON.stringify(["/images/products/puerta-fresada.jpg"]),
      categoryId: "puertas",
      subcategoryId: "puertas-fresadas",
      features: JSON.stringify(["Doble ranura", "Melamina roble", "Marco incluido"]),
      isActive: true,
    },
    {
      slug: "puerta-fresada-f530",
      name: "Puerta Fresada F-530 Premium",
      code: "F-530",
      description: "Puerta fresada de 4 ranuras con acabado lacado blanco.",
      price: 389.0,
      stock: 12,
      images: JSON.stringify(["/images/products/puerta-fresada-premium.jpg"]),
      categoryId: "puertas",
      subcategoryId: "puertas-fresadas",
      features: JSON.stringify(["4 ranuras", "Lacado blanco", "Premarco incluido"]),
      isActive: true,
    },
    // PUERTAS LACADAS
    {
      slug: "puerta-lacada-blanco-mate",
      name: "Puerta Lacada Blanco Mate",
      code: "LAC-WM",
      description: "Puerta lacada en blanco mate. El acabado mas demandado del mercado.",
      price: 449.0,
      stock: 25,
      images: JSON.stringify(["/images/products/puerta-lacada-blanco.jpg"]),
      categoryId: "puertas",
      subcategoryId: "puertas-lacadas",
      features: JSON.stringify(["Lacado blanco mate", "Maxima resistencia", "Anti-huella"]),
      isActive: true,
    },
    {
      slug: "puerta-lacada-gris-perla",
      name: "Puerta Lacada Gris Perla",
      code: "LAC-GP",
      description: "Puerta lacada en gris perla. Acabado contemporaneo de alta calidad.",
      price: 469.0,
      stock: 18,
      images: JSON.stringify(["/images/products/puerta-lacada-gris.jpg"]),
      categoryId: "puertas",
      subcategoryId: "puertas-lacadas",
      features: JSON.stringify(["Gris perla", "Lacado UV", "Anti-huella"]),
      isActive: true,
    },
    // ARMARIOS ABATIBLES
    {
      slug: "armario-abatible-2-puertas",
      name: "Armario Abatible 2 Puertas",
      code: "ARM-AB2",
      description: "Armario empotrado con 2 puertas abatibles. Incluye interior completo.",
      price: 650.0,
      stock: 10,
      images: JSON.stringify(["/images/products/armario-abatible.jpg"]),
      categoryId: "armarios",
      subcategoryId: "armarios-abatibles",
      features: JSON.stringify(["2 puertas", "Interior completo", "Baldas regulables", "Barra colgador"]),
      isActive: true,
    },
    {
      slug: "armario-abatible-3-puertas",
      name: "Armario Abatible 3 Puertas",
      code: "ARM-AB3",
      description: "Armario empotrado con 3 puertas abatibles. Mayor capacidad de almacenaje.",
      price: 890.0,
      stock: 8,
      images: JSON.stringify(["/images/products/armario-abatible-3p.jpg"]),
      categoryId: "armarios",
      subcategoryId: "armarios-abatibles",
      features: JSON.stringify(["3 puertas", "Interior modular", "Cajones incluidos"]),
      isActive: true,
    },
    // ARMARIOS CORREDEROS
    {
      slug: "armario-corredera-basic",
      name: "Armario Corredera Basic",
      code: "ARM-COR-B",
      description: "Armario empotrado con puertas correderas. Sistema de deslizamiento silencioso.",
      price: 780.0,
      stock: 12,
      images: JSON.stringify(["/images/products/armario-corredera.jpg"]),
      categoryId: "armarios",
      subcategoryId: "armarios-correderos",
      features: JSON.stringify(["Deslizamiento silencioso", "Espejo opcional", "Interior personalizable"]),
      isActive: true,
    },
    {
      slug: "armario-corredera-premium",
      name: "Armario Corredera Premium",
      code: "ARM-COR-P",
      description: "Armario empotrado corredera con puertas de espejo. Maxima elegancia.",
      price: 1250.0,
      stock: 6,
      images: JSON.stringify(["/images/products/armario-corredera-premium.jpg"]),
      categoryId: "armarios",
      subcategoryId: "armarios-correderos",
      features: JSON.stringify(["Puertas de espejo", "Amortiguadores", "Interior premium", "Iluminacion LED"]),
      isActive: true,
    },
    // PUERTAS ACORAZADAS
    {
      slug: "puerta-acorazada-eco-t",
      name: "Puerta Acorazada ECO-T",
      code: "ACO-ECO-T",
      description: "Puerta acorazada ECO-T. Seguridad y diseno al mejor precio.",
      price: 890.0,
      stock: 5,
      images: JSON.stringify(["/images/products/acorazada-eco-t.jpg"]),
      categoryId: "acorazadas",
      subcategoryId: "eco-t",
      features: JSON.stringify(["Cerradura multipunto", "Resistencia al palancamiento", "5 puntos de anclaje"]),
      isActive: true,
    },
    {
      slug: "puerta-acorazada-thor-20",
      name: "Puerta Acorazada THOR-20",
      code: "ACO-THOR20",
      description: "Puerta acorazada de alta seguridad THOR-20. Proteccion nivel RC-2.",
      price: 1490.0,
      stock: 4,
      images: JSON.stringify(["/images/products/acorazada-thor.jpg"]),
      categoryId: "acorazadas",
      subcategoryId: "thor-20",
      features: JSON.stringify(["Nivel RC-2", "Cerradura 5 puntos", "Acero reforzado", "Burlete corta-fuegos"]),
      isActive: true,
    },
    // MARCOS Y MOLDURAS
    {
      slug: "cerco-madera-70",
      name: "Cerco de Madera 70mm",
      code: "CER-70",
      description: "Cerco de madera maciza para puerta de paso. Ancho 70mm.",
      price: 45.0,
      stock: 100,
      images: JSON.stringify(["/images/products/cerco-madera.jpg"]),
      categoryId: "marcos-molduras",
      subcategoryId: "cercos",
      features: JSON.stringify(["Madera maciza", "70mm de ancho", "Barnizable", "Disponible en varios acabados"]),
      isActive: true,
    },
    {
      slug: "cerco-lacado-80",
      name: "Cerco Lacado Blanco 80mm",
      code: "CER-LAC-80",
      description: "Cerco lacado en blanco para puerta de paso. Ancho 80mm.",
      price: 65.0,
      stock: 75,
      images: JSON.stringify(["/images/products/cerco-lacado.jpg"]),
      categoryId: "marcos-molduras",
      subcategoryId: "cercos",
      features: JSON.stringify(["Lacado blanco", "80mm de ancho", "MDF de alta densidad"]),
      isActive: true,
    },
    {
      slug: "moldura-clasica-60",
      name: "Moldura Clasica 60mm",
      code: "MOL-CL60",
      description: "Moldura decorativa clasica para marco de puerta. 60mm de ancho.",
      price: 12.5,
      stock: 200,
      images: JSON.stringify(["/images/products/moldura-clasica.jpg"]),
      categoryId: "marcos-molduras",
      subcategoryId: "molduras",
      features: JSON.stringify(["Perfil clasico", "60mm de ancho", "MDF lacable", "Precio por metro"]),
      isActive: true,
    },
    // HERRAJES
    {
      slug: "pomo-nilo-negro",
      name: "Pomo Nilo Negro Mate",
      code: "HER-POM-NIL-N",
      description: "Pomo redondo serie Nilo en acabado negro mate. Diseno minimalista.",
      price: 18.5,
      stock: 150,
      images: JSON.stringify(["/images/products/pomo-nilo.jpg"]),
      categoryId: "herrajes",
      subcategoryId: "pomos",
      features: JSON.stringify(["Negro mate", "Zamak de alta resistencia", "Tornilleria incluida"]),
      isActive: true,
    },
    {
      slug: "manilla-oslo-inox",
      name: "Manilla Oslo Acero Inox",
      code: "HER-MAN-OSL-I",
      description: "Manilla de palanca serie Oslo en acero inoxidable. Ergonomica y duradera.",
      price: 32.0,
      stock: 80,
      images: JSON.stringify(["/images/products/manilla-oslo.jpg"]),
      categoryId: "herrajes",
      subcategoryId: "manillones",
      features: JSON.stringify(["Acero inoxidable", "Acabado satinado", "Escudo largo incluido"]),
      isActive: true,
    },
    {
      slug: "bisagra-invisible-standard",
      name: "Bisagra Invisible Standard",
      code: "HER-BIS-INV",
      description: "Bisagra invisible de alta precision. Apertura 95 grados. Pack de 2 unidades.",
      price: 24.9,
      stock: 200,
      images: JSON.stringify(["/images/products/bisagra-invisible.jpg"]),
      categoryId: "herrajes",
      subcategoryId: "bisagras",
      features: JSON.stringify(["Invisible montada", "Apertura 95 grados", "Pack 2 ud.", "Regulacion 3D"]),
      isActive: true,
    },
    {
      slug: "cerradura-embutir-multipoint",
      name: "Cerradura Embutir Multipunto",
      code: "HER-CER-MP",
      description: "Cerradura de embutir con cierre multipunto. Maxima seguridad.",
      price: 89.0,
      stock: 40,
      images: JSON.stringify(["/images/products/cerradura-multipunto.jpg"]),
      categoryId: "herrajes",
      subcategoryId: "cerraduras",
      features: JSON.stringify(["3 puntos de cierre", "Paracentrica", "Compatible cilindro europeo"]),
      isActive: true,
    },
    // SOLUCIONES FENOLICAS
    {
      slug: "panel-fenolico-cabina-wc",
      name: "Panel Fenolico Cabina WC",
      code: "FEN-CAB-WC",
      description: "Panel compacto fenolico para cabinas de WC. Alta resistencia a la humedad.",
      price: 145.0,
      stock: 30,
      images: JSON.stringify(["/images/products/panel-fenolico-cabina.jpg"]),
      categoryId: "soluciones-fenolicas",
      subcategoryId: "cabinas",
      features: JSON.stringify(["Compacto HPL 13mm", "Resistente a humedad", "Facil limpieza", "Multitud de colores"]),
      isActive: true,
    },
    {
      slug: "panel-fenolico-fachada",
      name: "Panel Fenolico Fachada Ventilada",
      code: "FEN-FAC-V",
      description: "Panel fenolico para fachadas ventiladas. Resistente a UV y lluvia.",
      price: 220.0,
      stock: 15,
      images: JSON.stringify(["/images/products/panel-fenolico-fachada.jpg"]),
      categoryId: "soluciones-fenolicas",
      subcategoryId: "fachadas-ventiladas",
      features: JSON.stringify(["Clase A2-s1,d0", "UV resistente", "Facil instalacion", "Precio por m2"]),
      isActive: true,
    },
  ];

  for (const product of products) {
    await prisma.product.upsert({
      where: { slug: product.slug },
      update: product,
      create: product,
    });
  }

  console.log(`Seeded ${products.length} products`);
  await prisma.$disconnect();
}

seed().catch((e) => {
  console.error(e);
  process.exit(1);
});
